x-spark-image: &spark-image bitnami/spark:3.3.0

version: '3.5'
services:
  spark:
    container_name: spark
    image: *spark-image
    environment:
      - SPARK_MODE=master
    networks:
      - spark
    volumes:
      - ./work:/opt/bitnami/spark/work      
    restart: unless-stopped      
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"
      - "18080:18080"                      
  spark_node:
    container_name: spark_node
    image: *spark-image
    depends_on:
      - spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"         
    networks:
      - spark
    restart: unless-stopped            
networks:
  spark:
    driver: bridge